version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    # Cambiado a formato string para evitar errores de validación
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      timeout: 5s
      retries: 10
      interval: 10s
    networks:
      - back-net

  mock-api:
    image: node:18-alpine
    container_name: mock-api
    working_dir: /app
    volumes:
      - ./front_despacho:/app
    ports:
      - "3000:3000"
    command: npx json-server --watch db.json --host 0.0.0.0
    networks:
      - front-net

  back-despachos:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: back-despachos
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=${DB_ENDPOINT}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - back-net
      - front-net

  back-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: back-ventas
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=${DB_ENDPOINT}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - back-net
      - front-net

  frontend:
    build: ./front_despacho
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - back-despachos
      - back-ventas
      - mock-api
    networks:
      - front-net

networks:
  front-net:
  back-net:

volumes:
  mysql_data:
    driver: local